class Data:

    name = 'Tester1234'
    email = 'tester1234@sample.com'
    password = 'secretpassword'
    birthday = '1'
    birthmonth = 'January'
    birthyear = '2000'
    firstname = 'Tester'
    lastname = 'Tester'
    company = 'Testing Company'
    address = 'Random adress 1'
    secondaddress = 'Random address 2'
    country = 'United States'
    state = 'Montana'
    city = 'Billings'
    zipcode = '59101'
    mobile = '+012345678909'
